Feature/phase 6
desmos-labs/scoreboard pull request #21
Opened 2020-11-02 09:53 UTC by YuhsinLiao1995

## Description
added Phase 6 tab and integrated the query with polling for real-time data

## Checklist
- [v] Ran Linting
- [v] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [v] Wrote unit tests.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [v] Re-reviewed `Files changed` in the Github PR explorer.

2020-11-02 12:47 UTC, ryuash requested changes
Looks great!!! Can you just fix the typos and remove any unused code? :D

2020-11-02 12:47 UTC, ryuash commented on public/static/locales/en/desmos_primer.json
> +  "createdRelationship": "Created RelationShip",
relationship not RelationShip

2020-11-02 12:47 UTC, ryuash commented on src/screens/desmos_primer/components/phase_six/hooks.tsx
> +export const usePhaseFiveHook = () => {
usePhaseSixHook

2020-11-02 12:47 UTC, ryuash commented on src/screens/desmos_primer/components/phase_six/hooks.tsx
> +};
Actually I just took a look at the code. Can you show me where this is being imported and used??

2020-11-02 12:47 UTC, ryuash commented on src/screens/desmos_primer/components/phase_six/index.tsx
> +const PhaseFour = (props:IProps) => {
PhaseSix

2020-11-02 12:47 UTC, ryuash commented on src/screens/users/hooks.tsx
> +// const er = DesmosPrimerAll.
remove unused code

2020-11-03 01:49 UTC, YuhsinLiao1995 commented on src/screens/desmos_primer/components/phase_six/hooks.tsx
> +};
i found it is never used, so i deleted phase_six/hooks. and phase_five/hooks.

2020-11-03 03:44 UTC, merged